### ISSUE TITLE
Crash in multiplayer.

### ISSUE THREAD

**Issue by SeasonalFerret** [d0sboots/EnchantmentRevealer#3]
[crash-2018-06-17_10.19.04-client.txt](https://github.com/d0sboots/EnchantmentRevealer/files/2109106/crash-2018-06-17_10.19.04-client.txt)

Server: hypixel.net (skywars, enchanter kit)
Mods: EnchantmentRevealer-v1.1-1.8.9-1902
Forge: 1.8.9-forge1.8.9-11.15.1.1722

System details can be found within the crash log, but if you wish for any more information, please ask.

![Enchantment Screen](https://user-images.githubusercontent.com/17802843/41509389-67516ca2-7218-11e8-8a04-65239a1e485a.png)
After clicking an enchantment in the enchantment screen, I immediately crash.

**Comment by d0sboots** [comment]
Without digging into this very far, I have a fairly good suspicion of what happened. I'd guess that hypixel is changing something about how enchanting works? EnchantmentRevealer depends on being able to perform exactly the same calculations as the server for figuring out enchantments. It still shouldn't crash, of course, but if the client can't redo the same calculations the best it will be able to do is fall back to the default GUI.

**Comment by SeasonalFerret** [comment]
Not only did it not fall back to the default GUI, it also crashed.

**Comment by d0sboots** [comment]
Yes. What I meant was that the best it can theoretically do is fall back to the default GUI. It doesn't have code to try and handle this case yet (server modded to do different enchantments), so I'm not surprised that it doesn't work right currently. I'm a little surprised that it crashed, but hopefully that will make more sense when I dig into it more.

**Comment by d0sboots** [comment]
OK, (if you still care) v1.2 has a patch that avoids the immediate cause of the crash, although I'm not entirely sure what led up to that field never being set (and I can't reproduce the behavior), so I'm not 100% certain that it will eliminate similar crashes in the future.

The best bet remains to disable EnchantmentRevealer if you're on a server that radically changes how enchanting works.

The version you reported this on was Minecraft 1.8.9, and I didn't backport v1.2 that far, because between 1.8.9 and 1.9 there were significant changes to how enchanting works. If you're still playing 1.8.9, I can add just the one crash-fix patch and see if that improves things.

**Comment by SeasonalFerret** [comment]
Oh I still care a hell about this mod. I'ma have me some fun with this!

That back-port would be nice, too.
